name: BlockParticles
main: me.badbones69.blockparticles.Main
version: 1.9.7
softdepend: [Multiverse-Core, MultiWorld]
description: Add particles to blocks!
commands:
  BlockParticle:
    description: Adds particles to blocks!
    aliases: [bp]