name: BlockParticles
author: BadBones69
version: ${project.version}
main: me.badbones69.blockparticles.Main
softdepend: [Multiverse-Core, MultiWorld]
description: Add particles to blocks!
api-version: 1.14

commands:
  BlockParticle:
    description: Adds particles to blocks!
    aliases: [bp]